Feature: OpenAPI Code Generation
Generate C# code from OpenAPI specifications

  Scenario: Generate class from schema type object
    Given the OpenAPI specification:
      """
      openapi: 3.0.0
      info:
        title: Sample API
        version: 1.0.0
      paths: {}
      components:
        schemas:
          Person:
            type: object
            properties:
              Name:
                type: string
              Age:
                type: integer
      """
    When the code generator is executed
    Then the following code should be generated for the class Person:
      """
      // <auto-generated/>
      using System;
      
      namespace SampleAPI
      {
        public class Person
          {
            public string? Name { get; set; }
      
            public int? Age { get; set; }
          }
      }
      """
    
  Scenario: Generate array type property
    Given the OpenAPI specification:
    """
    openapi: 3.0.0
    info:
      title: Sample API
      version: 1.0.0
    paths: {}
    components:
      schemas:
        Category:
          type: object
          properties:
            id:
              type: integer
              format: int64
              example: 1
            name:
              type: string
              example: Dogs
          xml:
            name: category
        Tag:
          type: object
          properties:
            id:
              type: integer
              format: int64
            name:
              type: string
          xml:
            name: tag
        Pet:
          required:
          - name
          - photoUrls
          type: object
          properties:
            id:
              type: integer
              format: int64
              example: 10
            name:
              type: string
              example: doggie
            category:
              $ref: '#/components/schemas/Category'
            photoUrls:
              type: array
              xml:
                wrapped: true
              items:
                type: string
                xml:
                  name: photoUrl
            tags:
              type: array
              xml:
                wrapped: true
              items:
                $ref: '#/components/schemas/Tag'
            status:
              type: string
              description: pet status in the store
              enum:
              - available
              - pending
              - sold
          xml:
            name: pet
    """
    When the code generator is executed
    Then the following code should be generated for the class Pet:
    """
    // <auto-generated/>
    using System;
    using System.Collections.Generic;
    
    namespace SampleAPI
    {
        public class Pet
        {
            public long? id { get; set; }
            required public string name { get; set; }
            public Category? category { get; set; }
            required public List<string> photoUrls { get; set; }
            public List<Tag>? tags { get; set; }
            public PetStatus? status { get; set; }
        }
    }
    """
        And the following code should be generated for the enum PetStatus:
        """
        // <auto-generated/>
        using System;
        using System.Text.Json.Serialization;

        namespace SampleAPI
        {
          [JsonConverter(typeof(JsonStringEnumConverter))]
          public enum PetStatus
          {
            [JsonStringEnumMemberName("available")]
            Available,
            [JsonStringEnumMemberName("pending")]
            Pending,
            [JsonStringEnumMemberName("sold")]
            Sold
          }
        }
        """

  Scenario: Generate enum from string schema definition
    Given the OpenAPI specification:
    """
    openapi: 3.0.0
    info:
      title: Sample API
      version: 1.0.0
    paths: {}
    components:
      schemas:
        PetStatus:
          type: string
          enum:
          - available
          - pending
          - sold
        Pet:
          type: object
          properties:
            status:
              $ref: '#/components/schemas/PetStatus'
    """
    When the code generator is executed
    Then the following code should be generated for the enum PetStatus:
    """
    // <auto-generated/>
    using System;
    using System.Text.Json.Serialization;

    namespace SampleAPI
    {
        [JsonConverter(typeof(JsonStringEnumConverter))]
        public enum PetStatus
        {
            [JsonStringEnumMemberName("available")]
            Available,
            [JsonStringEnumMemberName("pending")]
            Pending,
            [JsonStringEnumMemberName("sold")]
            Sold
        }
    }
    """
    And the following code should be generated for the class Pet:
    """
    // <auto-generated/>
    using System;

    namespace SampleAPI
    {
        public class Pet
        {
            public PetStatus? status { get; set; }
        }
    }
    """

  Scenario: Generate valid names for digit-prefixed and separator-only component keys
    Given the OpenAPI specification:
    """
    openapi: 3.0.0
    info:
      title: Sample API
      version: 1.0.0
    paths: {}
    components:
      schemas:
        200-response:
          type: object
        ---:
          type: object
        Container:
          type: object
          properties:
            response:
              $ref: '#/components/schemas/200-response'
            values:
              type: array
              items:
                $ref: '#/components/schemas/---'
    """
    When the code generator is executed
    Then the following code should be generated for the class Type200Response:
    """
    // <auto-generated/>
    using System;

    namespace SampleAPI
    {
        public class Type200Response
        {
        }
    }
    """
    And the following code should be generated for the class GeneratedType:
    """
    // <auto-generated/>
    using System;

    namespace SampleAPI
    {
        public class GeneratedType
        {
        }
    }
    """
    And the following code should be generated for the class Container:
    """
    // <auto-generated/>
    using System;
    using System.Collections.Generic;

    namespace SampleAPI
    {
        public class Container
        {
            public Type200Response? response { get; set; }
            public List<GeneratedType>? values { get; set; }
        }
    }
    """

  Scenario: Generate enum from integer schema definition
    Given the OpenAPI specification:
    """
    openapi: 3.0.0
    info:
      title: Sample API
      version: 1.0.0
    paths: {}
    components:
      schemas:
        Priority:
          type: integer
          enum:
          - 0
          - 1
          - 5
    """
    When the code generator is executed
    Then the following code should be generated for the enum Priority:
    """
    // <auto-generated/>
    using System;

    namespace SampleAPI
    {
        public enum Priority
        {
            Value0 = 0,
            Value1 = 1,
            Value5 = 5
        }
    }
    """

  Scenario: Generate enum from long-backed integer schema definition
    Given the OpenAPI specification:
    """
    openapi: 3.0.0
    info:
      title: Sample API
      version: 1.0.0
    paths: {}
    components:
      schemas:
        LongPriority:
          type: integer
          enum:
          - -9223372036854775808
          - 9223372036854775807
    """
    When the code generator is executed
    Then the following code should be generated for the enum LongPriority:
    """
    // <auto-generated/>
    using System;

    namespace SampleAPI
    {
        public enum LongPriority : long
        {
            Negative9223372036854775808 = -9223372036854775808L,
            Value9223372036854775807 = 9223372036854775807L
        }
    }
    """

  Scenario: Generate containing-schema-qualified names for duplicate inline enum properties
    Given the OpenAPI specification:
    """
    openapi: 3.0.0
    info:
      title: Sample API
      version: 1.0.0
    paths: {}
    components:
      schemas:
        Dog:
          type: object
          properties:
            status:
              type: string
              enum:
              - available
              - adopted
        Cat:
          type: object
          properties:
            status:
              type: string
              enum:
              - available
              - fostered
    """
    When the code generator is executed
    Then the following code should be generated for the class Dog:
    """
    // <auto-generated/>
    using System;

    namespace SampleAPI
    {
        public class Dog
        {
            public DogStatus? status { get; set; }
        }
    }
    """

    And the following code should be generated for the enum DogStatus:
    """
    // <auto-generated/>
    using System;
    using System.Text.Json.Serialization;

    namespace SampleAPI
    {
        [JsonConverter(typeof(JsonStringEnumConverter))]
        public enum DogStatus
        {
            [JsonStringEnumMemberName("available")]
            Available,
            [JsonStringEnumMemberName("adopted")]
            Adopted
        }
    }
    """
    And the following code should be generated for the class Cat:
    """
    // <auto-generated/>
    using System;

    namespace SampleAPI
    {
        public class Cat
        {
            public CatStatus? status { get; set; }
        }
    }
    """
    And the following code should be generated for the enum CatStatus:
    """
    // <auto-generated/>
    using System;
    using System.Text.Json.Serialization;

    namespace SampleAPI
    {
        [JsonConverter(typeof(JsonStringEnumConverter))]
        public enum CatStatus
        {
            [JsonStringEnumMemberName("available")]
            Available,
            [JsonStringEnumMemberName("fostered")]
            Fostered
        }
    }
    """

  Scenario: Generate primitive types for primitive component references
    Given the OpenAPI specification:
    """
    openapi: 3.0.0
    info:
      title: Sample API
      version: 1.0.0
    paths: {}
    components:
      schemas:
        Age:
          type: integer
        Person:
          type: object
          properties:
            age:
              $ref: '#/components/schemas/Age'
            previousAges:
              type: array
              items:
                $ref: '#/components/schemas/Age'
    """
    When the code generator is executed
    Then the following code should be generated for the class Person:
    """
    // <auto-generated/>
    using System;
    using System.Collections.Generic;

    namespace SampleAPI
    {
        public class Person
        {
            public int? age { get; set; }
            public List<int>? previousAges { get; set; }
        }
    }
    """

  Scenario: Generate unique inline enum name when component enum has the same name
    Given the OpenAPI specification:
    """
    openapi: 3.0.0
    info:
      title: Sample API
      version: 1.0.0
    paths: {}
    components:
      schemas:
        PetStatus:
          type: string
          enum:
          - archived
        Pet:
          type: object
          properties:
            status:
              type: string
              enum:
              - available
              - pending
    """
    When the code generator is executed
    Then the following code should be generated for the enum PetStatus:
    """
    // <auto-generated/>
    using System;
    using System.Text.Json.Serialization;

    namespace SampleAPI
    {
        [JsonConverter(typeof(JsonStringEnumConverter))]
        public enum PetStatus
        {
            [JsonStringEnumMemberName("archived")]
            Archived
        }
    }
    """
    And the following code should be generated for the class Pet:
    """
    // <auto-generated/>
    using System;

    namespace SampleAPI
    {
        public class Pet
        {
            public PetStatus2? status { get; set; }
        }
    }
    """
    And the following code should be generated for the enum PetStatus2:
    """
    // <auto-generated/>
    using System;
    using System.Text.Json.Serialization;

    namespace SampleAPI
    {
        [JsonConverter(typeof(JsonStringEnumConverter))]
        public enum PetStatus2
        {
            [JsonStringEnumMemberName("available")]
            Available,
            [JsonStringEnumMemberName("pending")]
            Pending
        }
    }
    """

  Scenario: Preserve original wire value when the member name cannot be recovered from it
    Given the OpenAPI specification:
    """
    openapi: 3.0.0
    info:
      title: Sample API
      version: 1.0.0
    paths: {}
    components:
      schemas:
        TaskStatus:
          type: string
          enum:
          - in-progress
    """
    When the code generator is executed
    Then the following code should be generated for the enum TaskStatus:
    """
    // <auto-generated/>
    using System;
    using System.Text.Json.Serialization;

    namespace SampleAPI
    {
        [JsonConverter(typeof(JsonStringEnumConverter))]
        public enum TaskStatus
        {
            [JsonStringEnumMemberName("in-progress")]
            InProgress
        }
    }
    """

  Scenario: Generate unique nested object name when component schema has the same name
    Given the OpenAPI specification:
    """
    openapi: 3.0.0
    info:
      title: Sample API
      version: 1.0.0
    paths: {}
    components:
      schemas:
        PetStatus:
          type: object
          properties:
            label:
              type: string
        Pet:
          type: object
          properties:
            status:
              type: object
              properties:
                code:
                  type: string
    """
    When the code generator is executed
    Then the following code should be generated for the class PetStatus:
    """
    // <auto-generated/>
    using System;

    namespace SampleAPI
    {
        public class PetStatus
        {
            public string? label { get; set; }
        }
    }
    """
    And the following code should be generated for the class Pet:
    """
    // <auto-generated/>
    using System;

    namespace SampleAPI
    {
        public class Pet
        {
            public PetStatus2? status { get; set; }
        }
    }
    """
    And the following code should be generated for the class PetStatus2:
    """
    // <auto-generated/>
    using System;

    namespace SampleAPI
    {
        public class PetStatus2
        {
            public string? code { get; set; }
        }
    }
    """

  Scenario: Generate long property for integer schema with int64 format
    Given the OpenAPI specification:
    """
    openapi: 3.0.0
    info:
      title: Sample API
      version: 1.0.0
    paths: {}
    components:
      schemas:
        Account:
          type: object
          properties:
            balance:
              type: integer
              format: int64
    """
    When the code generator is executed
    Then the following code should be generated for the class Account:
    """
    // <auto-generated/>
    using System;

    namespace SampleAPI
    {
        public class Account
        {
            public long? balance { get; set; }
        }
    }
    """

  Scenario: Generate int property for integer schema with int32 format
    Given the OpenAPI specification:
    """
    openapi: 3.0.0
    info:
      title: Sample API
      version: 1.0.0
    paths: {}
    components:
      schemas:
        Account:
          type: object
          properties:
            balance:
              type: integer
              format: int32
    """
    When the code generator is executed
    Then the following code should be generated for the class Account:
    """
    // <auto-generated/>
    using System;

    namespace SampleAPI
    {
        public class Account
        {
            public int? balance { get; set; }
        }
    }
    """

  Scenario: Generate float property for number schema with float format
    Given the OpenAPI specification:
    """
    openapi: 3.0.0
    info:
      title: Sample API
      version: 1.0.0
    paths: {}
    components:
      schemas:
        Measurement:
          type: object
          properties:
            value:
              type: number
              format: float
    """
    When the code generator is executed
    Then the following code should be generated for the class Measurement:
    """
    // <auto-generated/>
    using System;

    namespace SampleAPI
    {
        public class Measurement
        {
            public float? value { get; set; }
        }
    }
    """

  Scenario: Generate double property for number schema with double format
    Given the OpenAPI specification:
    """
    openapi: 3.0.0
    info:
      title: Sample API
      version: 1.0.0
    paths: {}
    components:
      schemas:
        Measurement:
          type: object
          properties:
            value:
              type: number
              format: double
    """
    When the code generator is executed
    Then the following code should be generated for the class Measurement:
    """
    // <auto-generated/>
    using System;

    namespace SampleAPI
    {
        public class Measurement
        {
            public double? value { get; set; }
        }
    }
    """

  Scenario: Generate double property for number schema with no format
    Given the OpenAPI specification:
    """
    openapi: 3.0.0
    info:
      title: Sample API
      version: 1.0.0
    paths: {}
    components:
      schemas:
        Measurement:
          type: object
          properties:
            value:
              type: number
    """
    When the code generator is executed
    Then the following code should be generated for the class Measurement:
    """
    // <auto-generated/>
    using System;

    namespace SampleAPI
    {
        public class Measurement
        {
            public double? value { get; set; }
        }
    }
    """

  Scenario: Generate DateTimeOffset property for string schema with date-time format
    Given the OpenAPI specification:
    """
    openapi: 3.0.0
    info:
      title: Sample API
      version: 1.0.0
    paths: {}
    components:
      schemas:
        Event:
          type: object
          properties:
            occurredAt:
              type: string
              format: date-time
    """
    When the code generator is executed
    Then the following code should be generated for the class Event:
    """
    // <auto-generated/>
    using System;

    namespace SampleAPI
    {
        public class Event
        {
            public global::System.DateTimeOffset? occurredAt { get; set; }
        }
    }
    """

  Scenario: Generate Guid property for string schema with uuid format
    Given the OpenAPI specification:
    """
    openapi: 3.0.0
    info:
      title: Sample API
      version: 1.0.0
    paths: {}
    components:
      schemas:
        Resource:
          type: object
          properties:
            id:
              type: string
              format: uuid
    """
    When the code generator is executed
    Then the following code should be generated for the class Resource:
    """
    // <auto-generated/>
    using System;

    namespace SampleAPI
    {
        public class Resource
        {
            public global::System.Guid? id { get; set; }
        }
    }
    """

  Scenario: Generate globally qualified date-time/uuid formats even when a component schema shares the framework type name
    Given the OpenAPI specification:
    """
    openapi: 3.0.0
    info:
      title: Sample API
      version: 1.0.0
    paths: {}
    components:
      schemas:
        Guid:
          type: object
          properties:
            label:
              type: string
        DateTimeOffset:
          type: object
          properties:
            label:
              type: string
        Resource:
          type: object
          properties:
            id:
              type: string
              format: uuid
            createdAt:
              type: string
              format: date-time
    """
    When the code generator is executed
    Then the following code should be generated for the class Resource:
    """
    // <auto-generated/>
    using System;

    namespace SampleAPI
    {
        public class Resource
        {
            public global::System.Guid? id { get; set; }
            public global::System.DateTimeOffset? createdAt { get; set; }
        }
    }
    """

  Scenario: Generate byte array property for string schema with byte format
    Given the OpenAPI specification:
    """
    openapi: 3.0.0
    info:
      title: Sample API
      version: 1.0.0
    paths: {}
    components:
      schemas:
        Attachment:
          type: object
          properties:
            content:
              type: string
              format: byte
    """
    When the code generator is executed
    Then the following code should be generated for the class Attachment:
    """
    // <auto-generated/>
    using System;

    namespace SampleAPI
    {
        public class Attachment
        {
            public byte[]? content { get; set; }
        }
    }
    """

  Scenario: Fall back to base type mapping for unknown format values
    Given the OpenAPI specification:
    """
    openapi: 3.0.0
    info:
      title: Sample API
      version: 1.0.0
    paths: {}
    components:
      schemas:
        Widget:
          type: object
          properties:
            code:
              type: string
              format: unknown-format
            count:
              type: integer
              format: unknown-format
            weight:
              type: number
              format: unknown-format
    """
    When the code generator is executed
    Then the following code should be generated for the class Widget:
    """
    // <auto-generated/>
    using System;

    namespace SampleAPI
    {
        public class Widget
        {
            public string? code { get; set; }
            public int? count { get; set; }
            public double? weight { get; set; }
        }
    }
    """

  Scenario: Generate long array property for integer array items with int64 format
    Given the OpenAPI specification:
    """
    openapi: 3.0.0
    info:
      title: Sample API
      version: 1.0.0
    paths: {}
    components:
      schemas:
        Ledger:
          type: object
          properties:
            balances:
              type: array
              items:
                type: integer
                format: int64
    """
    When the code generator is executed
    Then the following code should be generated for the class Ledger:
    """
    // <auto-generated/>
    using System;
    using System.Collections.Generic;

    namespace SampleAPI
    {
        public class Ledger
        {
            public List<long>? balances { get; set; }
        }
    }
    """
