using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Nodes;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.OpenApi;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace OpenApiSourceGenerator.Generators;

/// <summary>
/// Generates C# enum declarations from OpenAPI enum schemas
/// </summary>
public class EnumGenerator
{
    public EnumDeclarationSyntax GenerateEnum(string enumName, IOpenApiSchema schema)
    {
        if (!IsEnumSchema(schema))
        {
            throw new ArgumentException("Schema does not define enum values", nameof(schema));
        }

        var enumValues = schema.Enum;
        var generatedEnumName = enumName.ToPascalCase();
        var usedNames = new HashSet<string>(StringComparer.Ordinal) { generatedEnumName };
        var enumDeclaration = EnumDeclaration(generatedEnumName)
            .AddModifiers(Token(SyntaxKind.PublicKeyword))
            .AddMembers([.. enumValues.Select((value, index) => GenerateMember(value, schema.Type, index, usedNames))]);

        if (schema.Type is JsonSchemaType.String)
        {
            enumDeclaration = enumDeclaration.AddAttributeLists(
                AttributeList(SingletonSeparatedList(
                    Attribute(IdentifierName("JsonConverter"))
                        .WithArgumentList(AttributeArgumentList(SingletonSeparatedList(
                            AttributeArgument(TypeOfExpression(IdentifierName("JsonStringEnumConverter")))))))));
        }

        if (DetermineIntegerBackingTypeKeyword(schema) is { } backingTypeKeyword)
        {
            enumDeclaration = enumDeclaration.WithBaseList(
                BaseList(SingletonSeparatedList<BaseTypeSyntax>(
                    SimpleBaseType(PredefinedType(Token(backingTypeKeyword))))));
        }

        return enumDeclaration;
    }

public static bool IsEnumSchema(IOpenApiSchema schema)
    {
        return (schema.Type is JsonSchemaType.String or JsonSchemaType.Integer)
            && schema.Enum is { Count: > 0 };
    }

    public static CompilationUnitSyntax GenerateCompilationUnit(
        string namespaceName,
        EnumDeclarationSyntax enumDeclaration)
    {
        var namespaceDeclaration = NamespaceDeclaration(IdentifierName(namespaceName.ToPascalCase()))
            .AddMembers(enumDeclaration);

        var usings = new List<UsingDirectiveSyntax> { UsingDirective(ParseName("System")) };
        if (enumDeclaration.AttributeLists.Count > 0)
        {
            usings.Add(UsingDirective(ParseName("System.Text.Json.Serialization")));
        }

        return CompilationUnit()
            .AddUsings([.. usings])
            .AddMembers(namespaceDeclaration)
            .WithLeadingTrivia(
                Comment("// <auto-generated/>"),
                ElasticCarriageReturnLineFeed)
            .NormalizeWhitespace();
    }

    private static EnumMemberDeclarationSyntax GenerateMember(
        JsonNode enumValue,
        JsonSchemaType? schemaType,
        int index,
        ISet<string> usedNames)
    {
        var memberName = EnsureUniqueName(CreateMemberName(enumValue, schemaType, index), usedNames);
        var memberDeclaration = EnumMemberDeclaration(Identifier(memberName));

        if (schemaType is JsonSchemaType.Integer && TryGetIntegerValue(enumValue, out var integerValue))
        {
            memberDeclaration = memberDeclaration.WithEqualsValue(
                EqualsValueClause(CreateIntegerLiteral(integerValue)));
        }
        else if (schemaType is JsonSchemaType.String && TryGetStringValue(enumValue, out var stringValue))
        {
            // Preserves the original wire value, which PascalCasing the member name cannot always recover.
            memberDeclaration = memberDeclaration.AddAttributeLists(
                AttributeList(SingletonSeparatedList(
                    Attribute(IdentifierName("JsonStringEnumMemberName"))
                        .WithArgumentList(AttributeArgumentList(SingletonSeparatedList(
                            AttributeArgument(LiteralExpression(
                                SyntaxKind.StringLiteralExpression,
                                Literal(stringValue)))))))));
        }

        return memberDeclaration;
    }

    private static string CreateMemberName(JsonNode enumValue, JsonSchemaType? schemaType, int index)
    {
        if (schemaType is JsonSchemaType.Integer && TryGetIntegerValue(enumValue, out var integerValue))
        {
            return CreateIntegerMemberName(integerValue);
        }

        var rawName = TryGetStringValue(enumValue, out var stringValue)
            ? stringValue
            : enumValue.ToJsonString();

        var memberName = rawName.ToPascalCase();
        if (string.IsNullOrEmpty(memberName))
        {
            memberName = $"Value{index + 1}";
        }

        if (char.IsDigit(memberName[0]))
        {
            memberName = $"Value{memberName}";
        }

        return memberName;
    }

    private static string CreateIntegerMemberName(decimal integerValue)
    {
        return integerValue < 0 ? $"Negative{Math.Abs(integerValue)}" : $"Value{integerValue}";
    }

    private static LiteralExpressionSyntax CreateIntegerLiteral(decimal integerValue)
    {
        if (integerValue >= int.MinValue && integerValue <= int.MaxValue)
        {
            return LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal((int)integerValue));
        }

        if (integerValue >= long.MinValue && integerValue <= long.MaxValue)
        {
            return LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal((long)integerValue));
        }

        if (integerValue >= ulong.MinValue && integerValue <= ulong.MaxValue)
        {
            return LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal((ulong)integerValue));
        }

        throw new NotSupportedException(
            $"Enum value {integerValue} cannot be represented by any C# enum backing type.");
    }

    private static string EnsureUniqueName(string memberName, ISet<string> usedNames)
    {
        var uniqueName = memberName;
        var suffix = 2;

        while (!usedNames.Add(uniqueName))
        {
            uniqueName = memberName + suffix;
            suffix++;
        }

        return uniqueName;
    }

    private static bool TryGetStringValue(JsonNode enumValue, out string value)
    {
        if (enumValue is JsonValue jsonValue && jsonValue.TryGetValue(out string? stringValue))
        {
            value = stringValue;
            return true;
        }

        value = string.Empty;
        return false;
    }

    private static bool TryGetIntegerValue(JsonNode enumValue, out decimal value)
    {
        if (enumValue is JsonValue jsonValue
            && jsonValue.TryGetValue(out decimal decimalValue)
            && decimalValue == decimal.Truncate(decimalValue))
        {
            value = decimalValue;
            return true;
        }

        value = 0;
        return false;
    }

    /// <summary>
    /// Picks the smallest C# enum backing type that fits every value, or throws when the schema
    /// contains an integer outside the range of any backing type (e.g. beyond ulong.MaxValue) rather
    /// than silently truncating it to a different wire value.
    /// </summary>
    private static SyntaxKind? DetermineIntegerBackingTypeKeyword(IOpenApiSchema schema)
    {
        if (schema.Type is not JsonSchemaType.Integer || schema.Enum is null)
        {
            return null;
        }

        decimal min = 0;
        decimal max = 0;
        var hasValue = false;

        foreach (var enumValue in schema.Enum)
        {
            if (!TryGetIntegerValue(enumValue, out var integerValue))
            {
                continue;
            }

            min = hasValue ? Math.Min(min, integerValue) : integerValue;
            max = hasValue ? Math.Max(max, integerValue) : integerValue;
            hasValue = true;
        }

        if (!hasValue || (min >= int.MinValue && max <= int.MaxValue))
        {
            return null;
        }

        if (min >= long.MinValue && max <= long.MaxValue)
        {
            return SyntaxKind.LongKeyword;
        }

        if (min >= ulong.MinValue && max <= ulong.MaxValue)
        {
            return SyntaxKind.ULongKeyword;
        }

        throw new NotSupportedException(
            $"Enum schema contains integer value(s) outside the range that can be represented by a "
            + $"C# enum backing type (min: {min}, max: {max}).");
    }
}