using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Nodes;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.OpenApi;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace OpenApiSourceGenerator.Generators;

/// <summary>
/// Generates C# enum declarations from OpenAPI enum schemas
/// </summary>
public class EnumGenerator
{
    public EnumDeclarationSyntax GenerateEnum(string enumName, IOpenApiSchema schema)
    {
        if (!IsEnumSchema(schema))
        {
            throw new ArgumentException("Schema does not define enum values", nameof(schema));
        }

        var enumValues = schema.Enum;
        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        var enumDeclaration = EnumDeclaration(enumName.ToPascalCase())
            .AddModifiers(Token(SyntaxKind.PublicKeyword))
            .AddMembers([.. enumValues.Select((value, index) => GenerateMember(value, schema.Type, index, usedNames))]);

        if (RequiresLongBackingType(schema))
        {
            enumDeclaration = enumDeclaration.WithBaseList(
                BaseList(SingletonSeparatedList<BaseTypeSyntax>(
                    SimpleBaseType(PredefinedType(Token(SyntaxKind.LongKeyword))))));
        }

        return enumDeclaration;
    }

    public static bool IsEnumSchema(IOpenApiSchema schema)
    {
        return schema.Enum is { Count: > 0 };
    }

    public static string CreateInlineEnumName(string containingSchemaName, string propertyName)
    {
        return containingSchemaName.ToPascalCase() + propertyName.ToPascalCase();
    }

    public static CompilationUnitSyntax GenerateCompilationUnit(
        string namespaceName,
        EnumDeclarationSyntax enumDeclaration)
    {
        var namespaceDeclaration = NamespaceDeclaration(IdentifierName(namespaceName.ToPascalCase()))
            .AddMembers(enumDeclaration);

        return CompilationUnit()
            .AddUsings(UsingDirective(ParseName("System")))
            .AddMembers(namespaceDeclaration)
            .WithLeadingTrivia(
                Comment("// <auto-generated/>"),
                ElasticCarriageReturnLineFeed)
            .NormalizeWhitespace();
    }

    private static EnumMemberDeclarationSyntax GenerateMember(
        JsonNode enumValue,
        JsonSchemaType? schemaType,
        int index,
        ISet<string> usedNames)
    {
        var memberName = EnsureUniqueName(CreateMemberName(enumValue, schemaType, index), usedNames);
        var memberDeclaration = EnumMemberDeclaration(Identifier(memberName));

        if (schemaType is JsonSchemaType.Integer && TryGetIntegerValue(enumValue, out var integerValue))
        {
            memberDeclaration = memberDeclaration.WithEqualsValue(
                EqualsValueClause(LiteralExpression(
                    SyntaxKind.NumericLiteralExpression,
                    integerValue >= int.MinValue && integerValue <= int.MaxValue
                        ? Literal((int)integerValue)
                        : Literal(integerValue))));
        }

        return memberDeclaration;
    }

    private static string CreateMemberName(JsonNode enumValue, JsonSchemaType? schemaType, int index)
    {
        if (schemaType is JsonSchemaType.Integer && TryGetIntegerValue(enumValue, out var integerValue))
        {
            return integerValue < 0 ? $"Negative{Math.Abs(integerValue)}" : $"Value{integerValue}";
        }

        var rawName = TryGetStringValue(enumValue, out var stringValue)
            ? stringValue
            : enumValue.ToJsonString();

        var memberName = rawName.ToPascalCase();
        if (string.IsNullOrEmpty(memberName))
        {
            memberName = $"Value{index + 1}";
        }

        if (char.IsDigit(memberName[0]))
        {
            memberName = $"Value{memberName}";
        }

        return memberName;
    }

    private static string EnsureUniqueName(string memberName, ISet<string> usedNames)
    {
        var uniqueName = memberName;
        var suffix = 2;

        while (!usedNames.Add(uniqueName))
        {
            uniqueName = memberName + suffix;
            suffix++;
        }

        return uniqueName;
    }

    private static bool TryGetStringValue(JsonNode enumValue, out string value)
    {
        if (enumValue is JsonValue jsonValue && jsonValue.TryGetValue(out string? stringValue))
        {
            value = stringValue;
            return true;
        }

        value = string.Empty;
        return false;
    }

    private static bool TryGetIntegerValue(JsonNode enumValue, out long value)
    {
        if (enumValue is not JsonValue jsonValue)
        {
            value = 0;
            return false;
        }

        if (jsonValue.TryGetValue(out int intValue))
        {
            value = intValue;
            return true;
        }

        if (jsonValue.TryGetValue(out long longValue))
        {
            value = longValue;
            return true;
        }

        if (jsonValue.TryGetValue(out decimal decimalValue)
            && decimalValue == decimal.Truncate(decimalValue)
            && decimalValue >= long.MinValue
            && decimalValue <= long.MaxValue)
        {
            value = (long)decimalValue;
            return true;
        }

        value = 0;
        return false;
    }

    private static bool RequiresLongBackingType(IOpenApiSchema schema)
    {
        return schema.Type is JsonSchemaType.Integer
            && schema.Enum.Any(value =>
                TryGetIntegerValue(value, out var integerValue)
                && (integerValue < int.MinValue || integerValue > int.MaxValue));
    }
}